<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2020/5/10
 * Time: 15:50
 */
namespace app\index\controller;

use think\Controller;

class Base extends Controller
{

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

}